# Generated by Django 5.1 on 2024-08-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=255, verbose_name='Title (Encrypted)')),
                ('_desc', models.CharField(max_length=255, verbose_name='Description (Encrypted)')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, verbose_name='Priority')),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=10, verbose_name='Category')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10, verbose_name='Status')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=255, verbose_name='Title (Encrypted)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=10, verbose_name='Status')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task', verbose_name='Parent Task')),
            ],
        ),
    ]
