# Generated by Django 5.1 on 2024-08-21 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title of the Task')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10, verbose_name='Status')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
